root: true
extends:
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:import/typescript"
  # - "google"
plugins:
  - "@typescript-eslint"
  - "prettier"
  - "import"
ignorePatterns:
  - "/lib/**/*" # Ignore built files.
env:
  es6: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  sourceType: module
rules:
  prettier/prettier: ["error"]
  # I quite like having explicit type defintiions so disable this rule.
  "@typescript-eslint/no-inferrable-types": "off"
  quotes: ["error", "double"]
  import/no-unresolved: 0
  indent: ["error", 2]
